/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef TICTACTOE_PRIVATE_H
#define TICTACTOE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.98"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	98
#define COMPANY_NAME	"AMX Infinity!"
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"A simple game of tic tac toe."
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"© Afaan Bilal"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Tic Tac Toe"
#define PRODUCT_VERSION	""

#endif /*TICTACTOE_PRIVATE_H*/
